[Structured Concurrency proposal]
Async/ await은 효율적인 비동기 코드를 작성하는 언어 메커니즘이다.
비동기 함수는 특정 suspension poiont에서 실행 중인 스레드를 포기할 수 있으며, 이는 동시성 시스템을 구축하는데 필요하다. 
func makeDinner() async throws -> Meal {
  let veggies = try await chopVegetables()
  let meat = await marinateMeat()
  let oven = try await preheatOven(temperature: 350)

  let dish = Dish(ingredients: [veggies, meat])
  return try await oven.cook(dish, duration: .hours(3))
}
위 코드를 보면, 비동기 함수들로 구현되어 있지만, 여전히 순서대로 실행된다.

Structured Concurrency는 "프로그래머"가 동시성을 고수준의 Task과 그 작업의 하위 작업으로 조직하도록 요구하는 개념이다.
기존의 스레드와 같은 저수준 개념 대신, 작업 단위로 관리할 수 있게 된다.

하위 작업을 계층적으로 관리하기 때문에 상위 작업에서 하위작업으로 하위에서 상위 작업으로 흐르게 된다. 
특징 

- 작업 취소
취소 API와 하위 작업으로 전파된다. 

- 작업 우선순위
우선순위 에스컬레이트가 가능하다.

- 컨텍스트 정보 전파
정보를 추상화 단계마다 일일이 전달하지 않기를 원한다. 그렇기 때문에 Task local storage도 존재함.

- 큐 오버플로 방지
동시성을 사용할 때 너무 많은 작업을 생성하려고 시도하면, 새로운 작업 생성을 중단하거나 지연시켜서 협럽적인 해결책을 제공


Tasks

동시성 시스템에서의 기본 단위이다.
모든 비동기 함수는 Task의 일부분으로 써 실행되며, 하나의 Task안에서는 하나의 함수만 실행이 가능하다.

3가지 상태가 존재하게 된다.
- Suspended 
해야할 작업이 존재하지만 아직 실행중이지 않을 때
    - schedulable 실행할 준비가 되었으며 시스템에 의해서 스레드에 배정되길 기다리는 상태

- Running
스레드에서 실행중인 상태를 뜻함
초기 함수에게 반환되기 전, 서스펜션 포인트에 도달하기 전 상태
서스펜션 포인트에서 즉시 schedulable이라면 엑터만 바꾸면 된다.

- Completed
더이상 처리할 작업이 존재하지 않을 때를 뜻하며 다른 상태로 전환될 수 없다.

비동기 함수는 해당 함수를 포함하는 작업이랑 동일한 스레드에서 실행될 것이다.

비동기 함수가 다른 비동기 함수에 의해서 불릴때 호출한 함수는 suspended 그러나 전체 테스크가 suspended된건 아니다.
함수의 입장에선 호출이 반환 되기를 기다리며, 일시 중지된 상태이다.
테스트 관점에서는 호출자에서 계속 실행중일 수도 있고, 다른 실행 컨텍스트로 변경하기 위해 일시 중단한거 일수도 있다.

작업은 크게 세가지 목적을 갖고 있다.
1. 작업 운선 순위와 같은 스케줄링 정보를 갖고 있다.
2. 작업을 취소, 완료 여부, 상태등을 조회할 수 있는 핸들러
3. Task local 데이터를 제공한다.

Child Tasks
비동기 함수는 차일드 테스크를 생성할 수 있다. 자식은 부모로 부터 우선 순위와 같은 정보를 상속 받지만 동시에 실행될 수도 있다.
자식 작업을 생성하는 함수는 작업이 끝날때 까지 기다렸다가 반환해야한다.

“Structure”의 뜻은 현재 작업에 대해 현재 수행 중인 모든 작업을 표시하고, 현재 작업을 취소했을 때 미치는 영향에 대해서 추론할 수 있는 걸 뜻합니다.
함수의 태스크가 다른 태스크의 자식일 수도 있고, 그 부모가 다른 자식을 가질 수도 있지만, 함수는 이를 local에서 추론하면 안된다.
추가적으로 취소와 같은 전체 작업 트리에 반영되는 것은 아래쪽으로만 전파되어야한다.

자 작업의 취소는 부모 작업으로 상향 전파되지 않는다.
그럼 어떻게 부모에서 에러를 잡는것이냐? 부모 작업은 자식 작업이 전부완료될 때까지 기다려야하는 의무가 있음
그렇기 때문에 자식 작업으로 부터 결과가 올때까지 기다리다 에러 핸들이 존재하면 그 플로우를 타는것이다.

우리의 접근 방식은 위에서 설명한 구조화된 동시성 원칙을 따릅니다. 
모든 비동기 함수는 비동기 작업의 일부로 실행됩니다. 
태스크는 동시에 작업을 수행할 하위 태스크를 만들 수 있습니다. 

Job
- 시스템에서 스케줄 가능한 작업의 기본 단위
- 비동기 함수가 동기적인 세꼐와 상호작용하는 기본적인 단위
- 비동기 함수는 여러 중단 지점을 거처 실행되며, 그 사이사이 구간을 잡이라고 부른다.

취소는 하향식 전파, 부모가 취소되면 자식도 취소
Local storage는 부모 작업에서 설정된 컨텐스트 정보가 자식으로 전파될 수 있으며, 상하향으로 흐를 수 있다. (Environment Key, Preference Key)
우선 순위 하향식 상속, 우선 순위가 상승되는 경우, 하위 작업에 영향을 줄 수 있다.
에러 및  핸들은 상항식 전파, 부모 작업이 자식 작업의 상태를 추적하고 관리하기 때문
Task의 상태는 상하향으로 흐른다.

Task group and child tasks
하위 작업을 만드는 방법 중 하나이며, 작업 그룹 범위 내의 하위작업은 범위가 종료될 때 까지 완료되야한다.
오류가 발생하여 범위가 종료될 경우 자식 작업은들은 암시적으로 먼저 취소된다.

TaskGroup을 직접 생성하는 방식이아닌, withTaskGroup을 사용해서 task group을 접근할 수 있고 addTask 메소드를 사용해서 하위 작업을 관리할 수 있다.
withTaskGroup의 실행이 끝났을 때 모든 서브 테스크가 완료됐다는걸 알수 있다.

그룹은 모든 자식 테스크가 끝날때 까지 기다린다.
“취소된 작업도 완료될 때까지 실행되어야 이함수가 반환된다.”

var veggies: [Vegetable]?

try await withThrowingTaskGroup(of: Void.self) { group in
  group.addTask {
    // error: mutation of captured var 'veggies' in concurrently-executing code
    veggies = try await chopVegetables()
  }
}
let dish = Dish(ingredients: [veggies!])

예를 들어, chopVegetables()에서 칼을 사용하는 과정에서 문제가 발생하여 에러가 발생하면, 해당 작업은 예외를 던지며 종료됩니다.
* 이때, 자식 작업인 야채 다지기 작업은 에러로 인해 완료됩니다.
* 이 에러는 부모 작업인 makeDinner()로 전파되며, 결과적으로 makeDinner() 함수는 예외와 함께 종료됩니다.
동시에, 아직 완료되지 않은 다른 자식 작업들(marinateMeat, preheatOven)은 자동으로 취소됩니다.
* 즉, 예외가 발생해 makeDinner()가 종료될 때, 미완료된 자식 작업들은 수동으로 취소할 필요 없이 자동으로 취소되며, 이를 구조화된 동시성에서 처리합니다.

/// Sequentially chop the vegetables.
func chopVegetables() async throws -> [Vegetable] {
  let rawVeggies: [Vegetable] = gatherRawVeggies()
  var choppedVeggies: [Vegetable] = []

  for v in rawVeggies {
    choppedVeggies.append(try await v.chopped())  <- 순서대로 작업 요청 후, 기다리는 현상 발생
  }

  return choppedVeggies
}


/// Concurrently chop the vegetables.
func chopVegetables() async throws -> [Vegetable] {
  // Create a task group where each child task produces a Vegetable.
  try await withThrowingTaskGroup(of: Vegetable.self) { group in 
    var rawVeggies: [Vegetable] = gatherRawVeggies()
    var choppedVeggies: [Vegetable] = []
    
    // Create a new child task for each vegetable that needs to be chopped.
    for v in rawVeggies {
      group.addTask { 
        try await v.chopped()
      }
    }

    // ***Wait for all of the chopping to complete, collecting the veggies into***
    // ***the result array in whatever order they're ready.***
    while let choppedVeggie = try await group.next() {
      choppedVeggies.append(choppedVeggie)
    }
    
    return choppedVeggies
  }
}


차일드 테스크는 범위를 넘어서 지속되지 않는다.
범위가 종료될 때까지 하위 작업이 완료되거나 암시적으로 기다려야한다.
오류를 통해 범위가 종료되면 하위작업은 대기하기전에 취소된다.

Structured concurrency는 수동적으로 에러를 전파하고 취소를 관리할 필요가 없음을 뜻한다.

Task Groups
withTaskGroup을 통해서 async context를 만들며, 동시적으로 실행될 새로운 태스크를 생성한다.

리턴되기 전 모든 테스크가 추가될 것을 보장해준다.

1. 작업 그룹 자체의 코드에 의해서 (next()를 호출해서 반환 값이 nil이 나올때 까지)
2. 암묵적으로 바디로 부터 리턴됐을 때

Creating TaskGroup child tasks
group.addTask는 작업 그룹에 하위 작업을 생성하여 지정된 작업 함수를 동시에 실행합니다.
하위 작업은 동일한 우선순위를 갖게된다 새로운 우선순위를 부여하기 전까지 일반적으로 우선순위를 직접 할당하지 말아줘요

extension ThrowingTaskGroup { 
  mutating func addTask(
    priority: TaskPriority? = nil,
    operation: @Sendable @escaping () async throws -> ChildTaskResult
  )
  
  mutating func addTaskUnlessCancelled(
    priority: TaskPriority? = nil,
    operation: @Sendable @escaping () async throws -> ChildTaskResult
  ) -> Bool
}
테스크 그룹에다가 추가하는건 항상 성공한다. 심지어 테스크가 캔슬되거나 그룹이 캔슬되었더라도.
그룹을 실행 중인 작업이 취소되거나 그룹을 명시적으로 취소된 경우에도 addTask는 항상 하위 작업을 집어넣는다.
작업 그룹이 이미 취소된 경우, 새 하위 작업은 취소된 상태로 만들어지긴한다.

"addTaskUnlessCancelled" 함수는 작업 생성을 시도하기 전에 그룹이 취소되었는지 확인하고 작업이 성공적으로 생성된 경우 참인 Bool을 반환합니다.
이를 통해 "취소될 때까지 작업을 계속 생성"해야 하는 그룹을 간단하게 구현할 수 있습니다.

“그룹의 특정 하위 테스크를 취소하더라도, 전체 그룹이나 그 형제 작업은 취소되지 않는다.”


Querying tasks in the group
Next() 오퍼레이션을 사용하면 그룹에서 생성된 작업의 결과를 수집할 수 있다.
그룹에 있는 작업 중 하나에서 정상적인 결과이든 오류가 발생했든 결과를 생성한다.

next가 반환하는 순서는 완료되는 순서
테스크 그룹은 또한 비동기 시퀀스 프로토콜을 준수하여 하위 태스크 결과가 대기 루프에서 반복될 수 있다.
== for in loops를 사용할 수 있다.

이 패턴을 사용하면 단일 작업에서 오류가 발생하면 오류가 본문 함수 및 작업 그룹 자체로 전파가 된다.

태스크 내부에서 에러를 핸들링하길 원한다면, nextResult를 사용해서 처리할 수 있다.

Task group cancellation
그룹을 캔슬 시키는 방법은 여러가지이다.
아래 모든 경우에 작업 그룹은 취소된다. 그룹에서 새로 만든 모든 작업은 취소된 상태로 시작된다.

1. withTaskThrowingGroup의 바디에서 에러를 던질 때
2. 그룹을 감싸는 테스크가 취소됐을 때
3. cancellAll이 호출됐을 때

Cancellation
취소는 대기 중인 자식 작업이 있는 범위에서 부모 작업이 오류를 발생시키는 경우와 같이 자동으로 트리거될 수 있다.

취소된 작업 내에서 취소의 효과는 완전히 협력적이고 동기적이다. 즉 취소를 확인하지 않는 이상 전혀 효럭이 없다.
취소는 비동기 함수 내에 추가적인 제어 흐름 경로를 생성하지 않는다, 항상 함수를 살펴보고 취소가 발생할 수 있는 위치를 확인해야한다.
이런 경우 defer를 사용하면 취소 후 처리를 알아보기 쉽다.

가장 좋은 경우는 비동기 함수가 취소 요청을 받으면 가능한 빨리 이를 처리하여 취소 오류를 전달하거나 적절한 반환을 통해 종료하는 것이다.
대부분의 비동기 함수는 I/O 작업이나 Task.value와 같은 하위 레벨 함수들이 취소 상태를 확인하고 적절하게 의존한다.

동기적인 계산이 많은 함수들은 주기적으로 취소 상태를 명시적으로 확인하는 게 좋다.

취소가 발생했을 때
1. 작업에서 취소된 것으로 표시하는 플래그가 셋되며, 플래그가 셋되면 변경되지 않는다.
작업의 일부로 동기적으로 실행되는 작업은 이 플래그를 확인할 수 있으며 일반적으로 취소 오류를 발생킬것을 예상된다.

2. 작업에 등록된 모든 취소 핸들러가 즉시 실행된다. 이를 통해 즉시 응답해야 하는 함수가 즉시 호출된다.

이전에 말했듯이 취소의 이펙트는 동기적이고 협력적이다.
동기적 계산이 많이 발생하는 함수는 명시적으로 취소를 확인하길 바란다.
작업의 상태를 확인하면 된다.



Unstructured tasks
fire-and-forget 작업이나 동기 코드에서 비동기 작업을 시작할 때는 작업의 생명주기가 부모 작업에 묶여 있을 필요가 없다.
이러한 상황에서 구조화되지 않는 작업을 사용한다.

Task 자체의 상태를 통해서 취소하거나 값을 사용할 수 있게 된다.
Task.init으로 생성할 수 있다.

let task = Task { async work }
let value = task.value
task.cancel()

Context inheritance
1. 작업 내부에서 생성된 경우
func hello() async {
    Task {
        -> Here
    }
}
- 우선순위
- local storage
- actor isoloation

2. 작업 외부 컨텍스트에서 생성되는 경우
- 우선순위 추론
- 런타임에 연관된 local storage  없는지 확인
- Global executor

Actors prevent this data race by specifying that a @Sendable closure is always non-isolated.

Detached tasks
어느것도 상속받지 않음.
Task.detached
Global executor
